// Barrel export de todos los componentes atómicos de la UI
export { default as Button }      from './Button'
export { default as Input }       from './Input'
export { default as Card }        from './Card'
export { default as PageHeader }  from './PageHeader'
export { default as StatusBadge } from './StatusBadge'
export { default as Divider }     from './Divider'
export { default as TabBar }      from './TabBar'
export { default as Select }      from './Select'
export { default as CharacterCounter } from './CharacterCounter'
export { default as Textarea }         from './Textarea'
export { default as SearchableSelect } from './SearchableSelect'
export { default as QuantityInput }    from './QuantityInput'
export { default as ConfirmationModal } from './ConfirmationModal'
export { default as InsumoFormModal } from './InsumoFormModal'
export { default as TemplateFormModal } from './TemplateFormModal'

